// Markdown report generator — pure function with no DOM dependencies.
// Can be used from the popup Report view, options page, or background script.

import type { CategoryMapping, MoveOperation, Place } from "./types";
import { resolveTargetList } from "./config";

export interface ReportInput {
  listName: string;
  places: Place[];
  categoryMappings: CategoryMapping[];
  fallbackList: string;
}

interface ReportData {
  healthy: Place[];
  permClosed: Place[];
  tempClosed: Place[];
  notFound: Place[];
  problems: Place[];
  categoryBreakdown: [string, number][];
  suggestedMoves: MoveOperation[];
}

/**
 * Analyze audited places and compute all derived data used by the report.
 */
export function analyzeAudit(input: ReportInput): ReportData {
  const { listName, places, categoryMappings, fallbackList } = input;

  const healthy = places.filter((p) => p.status === "open");
  const permClosed = places.filter((p) => p.status === "permanently_closed");
  const tempClosed = places.filter((p) => p.status === "temporarily_closed");
  const notFound = places.filter((p) => p.status === "not_found");
  const problems = [...permClosed, ...tempClosed, ...notFound];

  // Category breakdown
  const counts = new Map<string, number>();
  for (const p of places) {
    if (p.categories.length === 0) {
      counts.set("(uncategorized)", (counts.get("(uncategorized)") ?? 0) + 1);
    } else {
      for (const cat of p.categories) {
        counts.set(cat, (counts.get(cat) ?? 0) + 1);
      }
    }
  }
  const categoryBreakdown = Array.from(counts.entries()).sort(
    (a, b) => b[1] - a[1],
  );

  // Suggested moves
  const suggestedMoves: MoveOperation[] = [];
  for (const p of healthy) {
    if (p.categories.length === 0) continue;
    const target = resolveTargetList(
      p.categories,
      categoryMappings,
      fallbackList,
    );
    if (target !== listName) {
      suggestedMoves.push({
        placeName: p.name,
        mapsUrl: p.mapsUrl,
        sourceList: listName,
        targetList: target,
      });
    }
  }

  return {
    healthy,
    permClosed,
    tempClosed,
    notFound,
    problems,
    categoryBreakdown,
    suggestedMoves,
  };
}

/**
 * Generate a full Markdown audit report from analyzed data.
 */
export function generateMarkdownReport(
  input: ReportInput,
  data?: ReportData,
): string {
  const d = data ?? analyzeAudit(input);
  const { listName, places } = input;

  const lines: string[] = [];

  // Header
  lines.push(`# Audit Report: ${listName}`);
  lines.push("");
  lines.push(`**Total places:** ${places.length}`);
  lines.push(
    `**Open:** ${d.healthy.length} | ` +
      `**Problems:** ${d.problems.length} ` +
      `(${d.permClosed.length} permanently closed, ` +
      `${d.tempClosed.length} temporarily closed, ` +
      `${d.notFound.length} not found)`,
  );
  lines.push("");

  // Problems
  if (d.problems.length > 0) {
    lines.push("## Problems");
    lines.push("");

    if (d.permClosed.length > 0) {
      lines.push(`### Permanently Closed (${d.permClosed.length})`);
      lines.push("");
      for (const p of d.permClosed) {
        lines.push(`- [${p.name}](${p.mapsUrl})`);
      }
      lines.push("");
    }

    if (d.tempClosed.length > 0) {
      lines.push(`### Temporarily Closed (${d.tempClosed.length})`);
      lines.push("");
      for (const p of d.tempClosed) {
        lines.push(`- [${p.name}](${p.mapsUrl})`);
      }
      lines.push("");
    }

    if (d.notFound.length > 0) {
      lines.push(`### Not Found (${d.notFound.length})`);
      lines.push("");
      for (const p of d.notFound) {
        lines.push(`- [${p.name}](${p.mapsUrl})`);
      }
      lines.push("");
    }
  }

  // Category breakdown
  if (d.categoryBreakdown.length > 0) {
    lines.push("## Category Breakdown");
    lines.push("");
    lines.push("| Category | Count |");
    lines.push("|----------|------:|");
    for (const [cat, count] of d.categoryBreakdown) {
      lines.push(`| ${cat} | ${count} |`);
    }
    lines.push("");
  }

  // Suggested moves
  if (d.suggestedMoves.length > 0) {
    lines.push(`## Suggested Moves (${d.suggestedMoves.length})`);
    lines.push("");
    lines.push("| Place | From | To |");
    lines.push("|-------|------|----|");
    for (const op of d.suggestedMoves) {
      lines.push(`| ${op.placeName} | ${op.sourceList} | ${op.targetList} |`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by gmaps-tidy on ${new Date().toLocaleDateString()}*`,
  );

  return lines.join("\n");
}
